version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5532:5432"

